### ISSUE TITLE
License

### ISSUE THREAD

**Issue by fakerybakery** [facebookresearch/audio2photoreal#21]
Hi,
Thank you for releasing this code. Do you have any plans to release it under an **open-sourced** license (ie Apache, MIT, ISC)?
Thank you!

**Comment by alexanderrichard** [comment]
No, the code will remain under the non-commercial license it is released under now.

**Comment by fakerybakery** [comment]
Thanks!

**Comment by alexanderrichard** [comment]
To comply with the consent participants gave for their data to be used in this study, the license has to stay as is. Sorry.
