### ISSUE TITLE
Data seems unavailable

### ISSUE THREAD

**Issue by bbqq7788** [facebookresearch/audio2photoreal#22]
When I wanted to reproduce this paper, I found that the data was unavailable at https://github.com/facebookresearch/audio2photoreal/releases/download/v1.0/<PXB184>.zip or sh scripts/download_allmodels .sh

**Comment by alexanderrichard** [comment]
It seems that github releases block downloads from command line. We will look into it.
In the meantime, you can download the four zip files manually here:
https://github.com/facebookresearch/audio2photoreal/releases

**Comment by alexanderrichard** [comment]
Issue is now resolved.
