### ISSUE TITLE
hardware requirements？

### ISSUE THREAD

**Issue by yitenghao** [facebookresearch/audio2photoreal#23]
What specifications of GPU and CPU are needed？

**Comment by prinshul** [comment]
> For the paper we used a A100, but we also tested on a Titan XP and a Tesla T4 and both work fine with smaller batch sizes. It is also possible to run on the cpu during test time but it will take much longer.
> 
> Hope this helps!!

A100 40gb?

What is the total training time and how much time needed to do inference/testing?

Thanks
