### ISSUE TITLE
How to downgrade python version on Colab to 3.9

### ISSUE THREAD

**Issue by abishpius** [facebookresearch/audio2photoreal#25]
https://www.geeksforgeeks.org/how-to-downgrade-python-version-in-colab/

tl;dr
step1: !sudo apt-get install python3.9
step2: !sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.9 1

reap the benefits: !python --version

**Comment by evonneng** [comment]
Oh awesome! Thanks a bunch for this pointer. I’ll test it out and update the collab soon 😊

**Comment by abishpius** [comment]
You will also need to use !pip3 in all the future executions of pip just fyi
