### ISSUE TITLE
soundfile.LibsndfileError: Error opening '/tmp/audio_tmp_sample0.wav': System error.

### ISSUE THREAD

**Issue by KelvinHuang66** [facebookresearch/audio2photoreal#27]
soundfile.LibsndfileError: Error opening '/tmp/audio_tmp_sample0.wav': System error.
when I  suppored my audio in windows.

**Comment by evonneng** [comment]
Hi! hmm it's likely the audio file is corrupted in some way. Could you check to see if you can open and play the audio saved at that location please? Otherwise will need more information to help with the debugging.

**Comment by alexanderrichard** [comment]
Could also be related to this issue https://github.com/facebookresearch/audio2photoreal/issues/11

**Comment by evonneng** [comment]
Closing for now due to inactivity, but please feel free to reopen if needed!

**Comment by nitinmukesh** [comment]
@KelvinHuang66 

Did you managed to solve this error.
