### ISSUE TITLE
No audio I/O backend is available.

### ISSUE THREAD

**Issue by MadeByKit** [facebookresearch/audio2photoreal#28]
(a2p_env) C:\Users\kit\audio2photoreal>python -m train.train_vq --out_dir checkpoints/vq/c1_vq_test --data_root ./dataset/PXB184/ --lr 1e-3 --code_dim 1024 --output_emb_width 64 --depth 4 --dataname social --loss_vel 0.0 --data_format pose --batch_size 4 --add_frame_cond 1 --max_seq_length 600
C:\Users\kit\miniconda3\envs\a2p_env\lib\site-packages\torchaudio\backend\utils.py:74: UserWarning: No audio backend is available.
  warnings.warn("No audio backend is available.")
2024-01-10 09:11:43,820 INFO {
    "add_frame_cond": 1.0,
    "batch_size": 4,
    "code_dim": 1024,
    "commit": 0.02,
    "data_format": "pose",
    "data_root": "./dataset/PXB184/",
    "dataname": "social",
    "dataset": "social",
    "depth": 4,
    "eval_iter": 1000,
    "gamma": 0.05,
    "loss_vel": 0.0,
    "lr": 0.001,
    "lr_scheduler": [
        300000
    ],
    "max_seq_length": 600,
    "out_dir": "checkpoints/vq/c1_vq_test",
    "output_emb_width": 64,
    "print_iter": 200,
    "resume_pth": null,
    "seed": 123,
    "total_iter": 300000,
    "warm_up_iter": 1000,
    "weight_decay": 0.0
}
Traceback (most recent call last):
  File "C:\Users\kit\miniconda3\envs\a2p_env\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\kit\miniconda3\envs\a2p_env\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\kit\audio2photoreal\train\train_vq.py", line 374, in <module>
    main(args)
  File "C:\Users\kit\audio2photoreal\train\train_vq.py", line 321, in main
    train_loader_iter, val_loader, skip_step = _load_data_info(args, logger)
  File "C:\Users\kit\audio2photoreal\train\train_vq.py", line 275, in _load_data_info
    data_dict = load_local_data(args.data_root, audio_per_frame=1600)
  File "C:\Users\kit\audio2photoreal\data_loaders\get_data.py", line 125, in load_local_data
    return _load_pose_data(
  File "C:\Users\kit\audio2photoreal\data_loaders\get_data.py", line 79, in _load_pose_data
    curr_audio, _ = torchaudio.load(
  File "C:\Users\kit\miniconda3\envs\a2p_env\lib\site-packages\torchaudio\backend\no_backend.py", line 16, in load
    raise RuntimeError("No audio I/O backend is available.")
RuntimeError: No audio I/O backend is available.

**Comment by evonneng** [comment]
Hi! this seems like a windows issue for installing torchaudio, where you need to install an audio backend! Could you see these references please and see if any of them help? 
- https://gist.github.com/flashlin/218876b07e0db558c344bc0393c5b68c
- https://stackoverflow.com/questions/62543843/cannot-import-torch-audio-no-audio-backend-is-available

**Comment by genius92606** [comment]
Try
`pip install soundfile`

**Comment by genius92606** [comment]
> (a2p_env) C:\Users\kit\audio2photoreal>python -m train.train_vq --out_dir checkpoints/vq/c1_vq_test --data_root ./dataset/PXB184/ --lr 1e-3 --code_dim 1024 --output_emb_width 64 --depth 4 --dataname social --loss_vel 0.0 --data_format pose --batch_size 4 --add_frame_cond 1 --max_seq_length 600 C:\Users\kit\miniconda3\envs\a2p_env\lib\site-packages\torchaudio\backend\utils.py:74: UserWarning: No audio backend is available. warnings.warn("No audio backend is available.") 2024-01-10 09:11:43,820 INFO { "add_frame_cond": 1.0, "batch_size": 4, "code_dim": 1024, "commit": 0.02, "data_format": "pose", "data_root": "./dataset/PXB184/", "dataname": "social", "dataset": "social", "depth": 4, "eval_iter": 1000, "gamma": 0.05, "loss_vel": 0.0, "lr": 0.001, "lr_scheduler": [ 300000 ], "max_seq_length": 600, "out_dir": "checkpoints/vq/c1_vq_test", "output_emb_width": 64, "print_iter": 200, "resume_pth": null, "seed": 123, "total_iter": 300000, "warm_up_iter": 1000, "weight_decay": 0.0 } Traceback (most recent call last): File "C:\Users\kit\miniconda3\envs\a2p_env\lib\runpy.py", line 197, in _run_module_as_main return _run_code(code, main_globals, None, File "C:\Users\kit\miniconda3\envs\a2p_env\lib\runpy.py", line 87, in _run_code exec(code, run_globals) File "C:\Users\kit\audio2photoreal\train\train_vq.py", line 374, in main(args) File "C:\Users\kit\audio2photoreal\train\train_vq.py", line 321, in main train_loader_iter, val_loader, skip_step = _load_data_info(args, logger) File "C:\Users\kit\audio2photoreal\train\train_vq.py", line 275, in _load_data_info data_dict = load_local_data(args.data_root, audio_per_frame=1600) File "C:\Users\kit\audio2photoreal\data_loaders\get_data.py", line 125, in load_local_data return _load_pose_data( File "C:\Users\kit\audio2photoreal\data_loaders\get_data.py", line 79, in _load_pose_data curr_audio, _ = torchaudio.load( File "C:\Users\kit\miniconda3\envs\a2p_env\lib\site-packages\torchaudio\backend\no_backend.py", line 16, in load raise RuntimeError("No audio I/O backend is available.") RuntimeError: No audio I/O backend is available.

Try
`pip install soundfile`

**Comment by evonneng** [comment]
Closing now due to inactivity, but feel free to reopen as needed.
