### ISSUE TITLE
run error : No module named 'diffusion.respace' 

### ISSUE THREAD

**Issue by zazaji** [facebookresearch/audio2photoreal#32]
I installed it as per the readme, 
but running python demo/demo.py report an error:
 - No module named 'diffusion.respace'
 
Here's the lib version 
diffusion 6.10.1 
diffusion-core 0.0.40

the requirements.txt didnot give the exact version number, Ican't check the version. 
Or someone provide a requirements.txt with version numer?

Thanks.

**Comment by evonneng** [comment]
Hi! The diffusion package here shouldn't be a pip package. Instead, it is a module that is included in the repo (https://github.com/facebookresearch/audio2photoreal/blob/main/diffusion/respace.py)
Could you please try pip uninstalling your diffusion package and rerunning please?

**Comment by evonneng** [comment]
Going to close this for now due to inactivity, but please feel free to reopen if the problem persists!
