### ISSUE TITLE
Local url issue

### ISSUE THREAD

**Issue by sharmarkali93** [facebookresearch/audio2photoreal#38]
Hello question how to run the local url in google colab but it’s not working and can you help me how to use it and how it works

**Comment by alexanderrichard** [comment]
Hi! Could you point to where exactly the issue occurs and provide some more details please?

**Comment by sharmarkali93** [comment]
i tried to use the running on local url is 127.0.0.1:7860

**Comment by sharmarkali93** [comment]
after i follow the instructions properly and it's not working is the local url is 127.0.0.1:7860

**Comment by evonneng** [comment]
Hi! I believe you would have to port forward the local url to get it working. Otherwise, there should be an associated public URL that you can use that should work just by clicking on it.

**Comment by evonneng** [comment]
Will close this issue for now, but feel free to reopen if needed.
