### ISSUE TITLE
what are 256 facial codes?

### ISSUE THREAD

**Issue by Owen1234560** [facebookresearch/audio2photoreal#40]
Thanks for sharing this projetct!
Does the 256-dimensional expression vector have any specific meaning? Similar to iPhone arkit52, https://arkit-face-blendshapes.com/.

**Comment by evonneng** [comment]
Hi! thanks for your question. Unfortunately the expression vector was implicitly learned, so there isnt an explicit representation or interpretation for each dimension. 
But in case this is helpful, here are a few links to learn more about the process:
- "Deep Appearance Models for Face Rendering" (https://arxiv.org/abs/1808.00362)
- code + data: https://github.com/facebookresearch/multiface
