### ISSUE TITLE
video instructions.

### ISSUE THREAD

**Issue by sharmarkali93** [facebookresearch/audio2photoreal#42]
can you show me proper instructions and i really can't make an avatar properly and it doesn't have proper instructions in abstract and github but can you help me with the instructions in the video.

**Comment by Rishabh01msfi** [comment]
Getting this error again and again while running the python command over colab
![image](https://github.com/facebookresearch/audio2photoreal/assets/163506147/8f01644e-66f9-477e-bc13-b44a8b20fee2)
