### ISSUE TITLE
About classifier-free guidance train policy

### ISSUE THREAD

**Issue by Zessay** [facebookresearch/audio2photoreal#43]
Thanks for your excellent work!

I find it says you adopt `classifier-free guidance` policy to train the diffusion module in the paper, as it shows in the following picture.

<img width="493" alt="image" src="https://github.com/facebookresearch/audio2photoreal/assets/39905704/879280ae-f76d-405b-a525-c43ad38cdac6">

However, in your codes, I find the `cond_mode` parameter is set when `FinLMTransformer` model is initialized, and won't change in the `TrainLoop`. Moreover, the `forward` function of the `FiLMtranformer` only uses the `cond_mode` of the model instance,  doesn't use the condition signal in the `y`.
<img width="300" alt="image" src="https://github.com/facebookresearch/audio2photoreal/assets/39905704/e2dc39a9-d796-40e9-93fb-c022b7e5a69c">

<img width="300" alt="image" src="https://github.com/facebookresearch/audio2photoreal/assets/39905704/c38a6a03-b2d7-41af-8dda-fa00e81cec62">

So, **I wonder whether the `classifier-free guidance` is used in the training process?**  Looking forward to your reply!

**Comment by Zessay** [comment]
I in-depth study the codes, and I think the `null_cond_embed` in the `FiLMTransformer` is used as `classifier-free guidance` and the `cond_drop_prob` is used as control signal, while the `ClassifierFreeSampleModel` doesn't work. Is it right?
<img width="300" alt="image" src="https://github.com/facebookresearch/audio2photoreal/assets/39905704/88fe498e-d0e1-4175-a054-d52af37ed002">
<img width="300" alt="image" src="https://github.com/facebookresearch/audio2photoreal/assets/39905704/7ede0c6d-210b-42d0-995e-a74be75a8c24">

**Comment by evonneng** [comment]
Hi! This is absolutely correct that this version of the CFG model is broken. Thanks so much for pointing this out! I'll open a PR right now to fix this issue, will run a few tests to make sure this is the one matching what the paper states.

**Comment by evonneng** [comment]
Closing now, after patch fix. Thanks for pointing this out! Please feel to reopen if needed.
