### ISSUE TITLE
Switching from Recording to Uploading Audio in a Demo: Is it Possible?

### ISSUE THREAD

**Issue by idarous4** [facebookresearch/audio2photoreal#51]
Is it possible to switch from recording audio to uploading audio in the demo? I tried changing gr.Audio(sources=["microphone"]) to gr.File() in the demo script. While I can upload audio successfully, it doesn't display anything afterward. Can this be resolved?
![audio](https://github.com/facebookresearch/audio2photoreal/assets/87344645/8238ae0d-032f-4e2e-8915-d8c137b3903e)

**Comment by evonneng** [comment]
Hi! Thanks for your question. It seems that providing support for both of them requires some toggling feature which I will look into later. But in the meantime, it seems you might have to change `microphone` to `upload` instead.

Please see this link for reference: https://www.gradio.app/docs/audio
