### ISSUE TITLE
Why the data is not as in the README ?

### ISSUE THREAD

**Issue by ABH2024** [facebookresearch/audio2photoreal#52]
Hello, 
First of all thank you for your work ! 
I am trying to run the code locally (demo and trying to do the training ) and i wanted to view the dataset to understand better how the model works but in the dataset folder there is only the **data_stats.pth** file. Where can i find the  audio files, the body pose etc . As mentionned in the  README.

Thank you for your time.
A.B.H

**Comment by alexanderrichard** [comment]
Hi,
you first need to download the dataset. Due to it's size, it's not part of the github repository. Just follow the instructions in the README:
https://github.com/facebookresearch/audio2photoreal?tab=readme-ov-file#download-data-and-models

**Comment by ABH2024** [comment]
Thank you very much !
