### ISSUE TITLE
Models and pre-requisites models unavailable

### ISSUE THREAD

**Issue by xxl007** [facebookresearch/audio2photoreal#53]
Hello,

Thanks for this amazing contribution. It seems that the models and pre-requisites are currently not available for download at http://audio2photoreal_models.berkeleyvision.org/. 

Therefore installation scripts are currently not functional.

Thanks

**Comment by evonneng** [comment]
Hi! Sorry for the inconvenience. It seems for some reason the berkeley servers hosting this dataset is down. I'm checking with our IT. otherwise, I will upload the models to a different link and ping this thread when they are read.

**Comment by xxl007** [comment]
Thanks very much for the quick reply @evonneng. Looking forward to being able to explore this amazing contribution.

**Comment by evonneng** [comment]
Thank you for your patience! The link should be fixed now!

**Comment by anitacen** [comment]
Hello,

It seems that the models and pre-requisites are not available again for download at http://audio2photoreal_models.berkeleyvision.org/.

Thanks
