### ISSUE TITLE
Models and pre-requisites models unavailable

### ISSUE THREAD

**Issue by soonwonh** [facebookresearch/audio2photoreal#55]
Though you have closed same issue #53 , it seems not solved .

seems that the models and pre-requisites are currently not available for download at http://audio2photoreal_models.berkeleyvision.org/.

**Comment by alexanderrichard** [comment]
We'll be looking into it and might move the assets to another, more stable server. Please stay tuned, sorry for the inconvenience.

**Comment by alexanderrichard** [comment]
The models are available again.

**Comment by SunwonHong96** [comment]
Thanks !

**Comment by soonwonh** [comment]
Thanks a lot!
