### ISSUE TITLE
Is it possible to run the demo in a laptop without GPU?

### ISSUE THREAD

**Issue by clabra** [facebookresearch/audio2photoreal#60]
Is there a way to run the demo in a laptop without GPU?. When I execute this in my MacOS BigSur 11.7.10., an error is raised: 

  python -m demo.demo
  running on... cpu  
  
  File ".... anaconda3/envs/audio2photoreal/lib/python3.9/site-packages/torch/cuda/__init__.py", line 239, in _lazy_init
      raise AssertionError("Torch not compiled with CUDA enabled")
  AssertionError: Torch not compiled with CUDA enabled

**Comment by evonneng** [comment]
Hi! I havent tried running on mac directly. If you only have access to cpu, I would suggest running using the google colab we have set up. There, you have access to at least 1 gpu and it should work with the command to install the environment. Hope this helps!

**Comment by chikiuso** [comment]
Good morning @evonneng , you mentioned the Colab notebook in previous message, may I have the link or copy of it? thanks!
