### ISSUE TITLE
Replancement of fairseq

### ISSUE THREAD

**Issue by SeanChenxy** [facebookresearch/audio2photoreal#64]
Hi, thanks for sharing the excellent work. I am trying to run this repo, but `fairseq` cannot be correctly imported because of the low version of `GLIBC`. I cannot update my environment. Hene, I wonder whether there are other methods without the use of `fairseq`. Thanks in advance.

**Comment by alexanderrichard** [comment]
Hey! You don't need fairseq. You could just copy the model definition from fairseq into a file so you can load the pretrained wav2vec model.
Alternatively, if you want to train from scratch, you can plug in any audio encoder of your choice, e.g. a wav2vec from another codebase than fairseq that you might have access to.
