### ISSUE TITLE
data_stats.pth file download link？

### ISSUE THREAD

**Issue by jim-1ee** [facebookresearch/audio2photoreal#77]
The zip link you provided does not have the data_stats.pth file, can you share the new link?
![e7c39d495e25ec7b9f59d864ae6889a0](https://github.com/user-attachments/assets/956e9ab1-9c59-49fa-ad3b-ac835e3ee522)

**Comment by evonneng** [comment]
Hi! thanks for your question! they should all already be in the github. e.g. https://github.com/facebookresearch/audio2photoreal/tree/main/dataset/GQS883

**Comment by jim-1ee** [comment]
谢谢~
